/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherContentRouteImport } from './routes/teacher.content'
import { Route as TeacherCertificatesRouteImport } from './routes/teacher.certificates'
import { Route as TeacherCalendarRouteImport } from './routes/teacher.calendar'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentCalendarRouteImport } from './routes/student.calendar'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAssignRouteImport } from './routes/admin.assign'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as StudentAssessmentsAssessmentIdRouteImport } from './routes/student.assessments.$assessmentId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherContentRoute = TeacherContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCertificatesRoute = TeacherCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCalendarRoute = StudentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignRoute = AdminAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const StudentAssessmentsAssessmentIdRoute =
  StudentAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/certificates': typeof TeacherCertificatesRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/assessments/$assessmentId': typeof StudentAssessmentsAssessmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/certificates': typeof TeacherCertificatesRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/assessments/$assessmentId': typeof StudentAssessmentsAssessmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/calendar': typeof StudentCalendarRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/messages': typeof StudentMessagesRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/certificates': typeof TeacherCertificatesRoute
  '/teacher/content': typeof TeacherContentRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/assessments/$assessmentId': typeof StudentAssessmentsAssessmentIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/verify'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/messages'
    | '/admin/users'
    | '/student/calendar'
    | '/student/certificates'
    | '/student/courses'
    | '/student/messages'
    | '/student/progress'
    | '/teacher/assessments'
    | '/teacher/calendar'
    | '/teacher/certificates'
    | '/teacher/content'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/assessments/$assessmentId'
    | '/student/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/messages'
    | '/admin/users'
    | '/student/calendar'
    | '/student/certificates'
    | '/student/courses'
    | '/student/messages'
    | '/student/progress'
    | '/teacher/assessments'
    | '/teacher/calendar'
    | '/teacher/certificates'
    | '/teacher/content'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/assessments/$assessmentId'
    | '/student/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/student'
    | '/teacher'
    | '/verify'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/calendar'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/messages'
    | '/admin/users'
    | '/student/calendar'
    | '/student/certificates'
    | '/student/courses'
    | '/student/messages'
    | '/student/progress'
    | '/teacher/assessments'
    | '/teacher/calendar'
    | '/teacher/certificates'
    | '/teacher/content'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/assessments/$assessmentId'
    | '/student/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/content': {
      id: '/teacher/content'
      path: '/content'
      fullPath: '/teacher/content'
      preLoaderRoute: typeof TeacherContentRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/certificates': {
      id: '/teacher/certificates'
      path: '/certificates'
      fullPath: '/teacher/certificates'
      preLoaderRoute: typeof TeacherCertificatesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/calendar': {
      id: '/student/calendar'
      path: '/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof StudentCalendarRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assign': {
      id: '/admin/assign'
      path: '/assign'
      fullPath: '/admin/assign'
      preLoaderRoute: typeof AdminAssignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/student/assessments/$assessmentId': {
      id: '/student/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/student/assessments/$assessmentId'
      preLoaderRoute: typeof StudentAssessmentsAssessmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignRoute: typeof AdminAssignRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignRoute: AdminAssignRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCalendarRoute: typeof StudentCalendarRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssessmentsAssessmentIdRoute: typeof StudentAssessmentsAssessmentIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCalendarRoute: StudentCalendarRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentAssessmentsAssessmentIdRoute: StudentAssessmentsAssessmentIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherCertificatesRoute: typeof TeacherCertificatesRoute
  TeacherContentRoute: typeof TeacherContentRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherCertificatesRoute: TeacherCertificatesRoute,
  TeacherContentRoute: TeacherContentRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
